  // represents the usage of an extension
  unknown-statement   = prefix ":" identifier [sep string] optsep
                        (";" /
                         "{" optsep
                             *((yang-stmt / unknown-statement) optsep)
                          "}") stmtsep

  yang-stmt           = action-stmt /
                        anydata-stmt /
                        anyxml-stmt /
                        argument-stmt /
                        augment-stmt /
                        base-stmt /
                        belongs-to-stmt /
                        bit-stmt /
                        case-stmt /
                        choice-stmt /
                        config-stmt /
                        contact-stmt /
                        container-stmt /
                        default-stmt /
                        description-stmt /
                        deviate-add-stmt /
                        deviate-delete-stmt /
                        deviate-not-supported-stmt /
                        deviate-replace-stmt /
                        deviation-stmt /
                        enum-stmt /
                        error-app-tag-stmt /
                        error-message-stmt /
                        extension-stmt /
                        feature-stmt /
                        fraction-digits-stmt /
                        grouping-stmt /
                        identity-stmt /
                        if-feature-stmt /
                        import-stmt /
                        include-stmt /
                        input-stmt /
                        key-stmt /
                        leaf-list-stmt /
                        leaf-stmt /
                        length-stmt /
                        list-stmt /
                        mandatory-stmt /
                        max-elements-stmt /
                        min-elements-stmt /
                        modifier-stmt /
                        module-stmt /
                        must-stmt /
                        namespace-stmt /
                        notification-stmt /
                        ordered-by-stmt /
                        organization-stmt /
                        output-stmt /
                        path-stmt /
                        pattern-stmt /
                        position-stmt /
                        prefix-stmt /
                        presence-stmt /
                        range-stmt /
                        reference-stmt /
                        refine-stmt /
                        require-instance-stmt /
                        revision-date-stmt /
                        revision-stmt /
                        rpc-stmt /
                        status-stmt /
                        submodule-stmt /
                        typedef-stmt /
                        type-stmt /
                        unique-stmt /
                        units-stmt /
                        uses-augment-stmt /
                        uses-stmt /
                        value-stmt /
                        when-stmt /
                        yang-version-stmt /
                        yin-element-stmt